function l(b,a,d,c){b.i.ka(b.N,a,d,c,void 0)}function p(b,a,d,c){b.i.o?l(b,a,d,c):b.i.ob()._OnMessageFromDOM({type:"event",component:b.N,handler:a,dispatchOpts:c||null,data:d,responseId:null})}function q(b,a,d){b.i.g(b.N,a,d)}function aa(b,a){for(const [d,c]of a)q(b,d,c)}window.Ha=class{constructor(b,a){this.i=b;this.N=a}Ea(){}};window.Tb=class{constructor(){}};"use strict";class ba{constructor(b){this.ra=b;this.ta=!1;this.wa=!0}}
function ca(b,a){const d=a.elementId,c=b.ha(d,a),e=new ba(c);b.O.set(d,e);c.style.boxSizing="border-box";c.style.display="none";e.wa=!!a.isVisible;a=b.ma(c);a.addEventListener("focus",()=>{r(b,"elem-focused",d)});a.addEventListener("blur",()=>{r(b,"elem-blurred",d)});b.$&&document.body.appendChild(c)}function t(b,a,d){q(b,a,c=>{const e=u(b,c.elementId);return d(e,c)})}function u(b,a){b=b.O.get(a);if(!b)throw Error(`no element with id ${a}`);return b.ra}
function r(b,a,d,c){c||(c={});c.elementId=d;l(b,a,c)}function v(b,a,d,c){c||(c={});c.elementId=d;p(b,a,c)}
window.Ga=class extends self.Ha{constructor(b,a){super(b,a);this.O=new Map;this.$=!0;aa(this,[["create",d=>ca(this,d)],["destroy",d=>{d=d.elementId;const c=u(this,d);this.$&&c.parentElement.removeChild(c);this.O.delete(d)}],["set-visible",d=>{if(this.$){var c=this.O.get(d.elementId),e=c.ra;c.ta?e.style.display=d.isVisible?"":"none":c.wa=!!d.isVisible}}],["update-position",d=>{if(this.$){var c=this.O.get(d.elementId),e=c.ra;e.style.left=d.left+"px";e.style.top=d.top+"px";e.style.width=d.width+"px";
e.style.height=d.height+"px";d=d.fontSize;null!==d&&(e.style.fontSize=d+"em");c.ta||(c.ta=!0,c.wa&&(e.style.display=""))}}],["update-state",d=>{const c=u(this,d.elementId);this.L(c,d)}],["focus",d=>{const c=this.ma(u(this,d.elementId));d.focus?c.focus():c.blur()}],["set-css-style",d=>{const c=u(this,d.elementId),e=d.prop;d=d.val;e.startsWith("--")?c.style.setProperty(e,d):c.style[e]=d}],["set-attribute",d=>{u(this,d.elementId).setAttribute(d.name,d.val)}],["remove-attribute",d=>{u(this,d.elementId).removeAttribute(d.name)}]]);
t(this,"get-element",d=>d)}ha(){throw Error("required override");}L(){throw Error("required override");}ma(b){return b}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),da=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let y=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Jb?new Promise(d=>{const c="c3_resolve_"+y;++y;self[c]=d;a.textContent=b.Nb+`\n\nself["${c}"]();`;document.head.appendChild(a)}):new Promise((d,c)=>{a.onload=d;a.onerror=c;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let A=new Audio;
const ia={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}
function ka(b){return new Promise((a,d)=>{const c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const D=[],E=new Map,F=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);let oa=!1;
window.X=class b{constructor(a){this.o=a.Pb;this.S=null;this.m="";this.G=a.Mb;this.W={};this.ya=this.I=null;this.aa=[];this.j=this.U=null;this.Ua=!1;this.P=null;this.F=-1;this.Eb=()=>this.vb();this.Ba=[];this.h=a.Xa;this.va="file"===location.protocol.substr(0,4);!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.o=!1);this.o&&da&&(this.o=!1);if("playable-ad"===this.h||"instant-games"===this.h)this.o=!1;if("cordova"===this.h&&this.o)if(x){const d=/Chrome\/(\d+)/i.exec(navigator.userAgent);
d&&90<=parseInt(d[1],10)||(this.o=!1)}else this.o=!1;this.ba=this.A=null;"html5"!==this.h||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.g("runtime","cordova-fetch-local-file",d=>this.rb(d));this.g("runtime","create-job-worker",()=>this.sb());"cordova"===this.h?document.addEventListener("deviceready",()=>this.La(a)):this.La(a)}bb(){return w&&
"cordova"===this.h}ja(){const a=navigator.userAgent;return w&&na.has(this.h)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}$a(){return x}Ia(){return x&&na.has(this.h)}async La(a){"macos-wkwebview"===this.h&&this.zb();if("playable-ad"===this.h){this.A=self.c3_base64files;this.ba={};await this.kb();for(let c=0,e=a.J.length;c<e;++c){var d=a.J[c];this.ba.hasOwnProperty(d)?a.J[c]={Jb:!0,Nb:this.ba[d]}:this.A.hasOwnProperty(d)&&(a.J[c]=URL.createObjectURL(this.A[d]))}a.ea=[]}if("nwjs"===this.h&&
self.nw&&self.nw.App.manifest["c3-steam-mode"]){let c=0;this.gb(()=>{c++;document.body.style.opacity=0===c%2?"1":"0.999"})}a.Lb?this.m=a.Lb:(d=location.origin,this.m=("null"===d?"file:///":d)+location.pathname,d=this.m.lastIndexOf("/"),-1!==d&&(this.m=this.m.substr(0,d+1)));a.Rb&&(this.W=a.Rb);d=new MessageChannel;this.S=d.port1;this.S.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.ub(c));this.P=new self.cb(this);await pa(this.P);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.o?await this.qb(a,d.port2):await this.pb(a,d.port2)}na(a){a=this.W.hasOwnProperty(a)?this.W[a]:a.endsWith("/workermain.js")&&this.W.hasOwnProperty("workermain.js")?this.W["workermain.js"]:"playable-ad"===this.h&&this.A.hasOwnProperty(a)?this.A[a]:
a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ia(a,d,c){if(a.startsWith("blob:"))return new Worker(a,c);if("cordova"===this.h&&this.va)return a=await this.ga(c.Ib?a:this.G+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),c);a=new URL(a,d);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}v(){return Math.max(window.innerWidth,
1)}u(){return Math.max(window.innerHeight,1)}Ka(a){var d=this.m,c=location.href,e=this.v(),f=this.u(),g=window.devicePixelRatio,h=b.K(),k=a.Xb,m=window.cr_previewImageBlobs||this.A,n=window.cr_previewProjectFileBlobs,Aa=window.cr_previewProjectFiles,Ba=window.Vb||"";a=a.Xa;var Ca=(new URLSearchParams(self.location.search)).has("debug"),L=this.P;return{runtimeBaseUrl:d,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,projectData:k,previewImageBlobs:m,previewProjectFileBlobs:n,
previewProjectFileSWUrls:Aa,swClientId:Ba,exportType:a,isDebug:Ca,ife:!!self.Wb,jobScheduler:{inputPort:L.ua,outputPort:L.Aa,maxNumWorkers:L.Cb},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.G+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.G+"opus.wasm.wasm",isFileProtocol:this.va,isiOSCordova:this.bb(),isiOSWebView:this.ja(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qb(a,d){const c=this.na(a.Qb);"preview"===this.h?(this.I=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((h,k)=>{const m=n=>{this.I.removeEventListener("message",m);n.data&&"ok"===n.data.type?h():k()};this.I.addEventListener("message",m);this.I.postMessage({type:"construct-worker-init","import":(new URL(c,this.m)).toString()})})):this.I=await this.ia(c,this.m,{type:"module",name:"Runtime",Ib:!0});this.j=document.createElement("canvas");this.j.style.display="none";const e=this.j.transferControlToOffscreen();document.body.appendChild(this.j);window.c3canvas=
this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=a.ea||[],g=a.J;f=await Promise.all(f.map(h=>this.D(h)));g=await Promise.all(g.map(h=>this.D(h)));if("cordova"===this.h)for(let h=0,k=a.da.length;h<k;++h){const m=a.da[h],n=m[0];if(n===a.Da||"scriptsInEvents.js"===n||n.endsWith("/scriptsInEvents.js"))m[1]=await this.D(n)}this.I.postMessage(Object.assign(this.Ka(a),{type:"init-runtime",isInWorker:!0,messagePort:d,canvas:e,workerDependencyScripts:f,engineScripts:g,projectScripts:a.da,
mainProjectScript:a.Da,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[d,e,...qa(this.P)]);this.aa=D.map(h=>new h(this));this.Ja();ra(this.U);self.c3_callFunction=(h,k)=>{var m=this.U;return m.i.eb(m.N,{name:h,params:k})};"preview"===this.h&&(self.goToLastErrorScript=()=>this.ka("runtime","go-to-last-error-script"))}async pb(a,d){this.j=document.createElement("canvas");this.j.style.display="none";document.body.appendChild(this.j);window.c3canvas=this.j;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.aa=D.map(g=>new g(this));this.Ja();var c=a.J.map(g=>"string"===typeof g?(new URL(g,this.m)).toString():g);if(Array.isArray(a.ea)){var e=[...a.ea].map(g=>g instanceof Blob?URL.createObjectURL(g):g);c.unshift(...e)}c=await Promise.all(c.map(g=>this.D(g)));await Promise.all(c.map(g=>z(g)));c=self.C3_ProjectScriptsStatus;e=a.Da;const f=a.da;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.D(h),await z(h),"preview"!==this.h||c[g]||this.Na(g,"main script did not run to completion")}catch(k){this.Na(g,
k)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.D(h),await z(h);"preview"===this.h&&"object"!==typeof self.Sb.Ub?(this.Z(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Ka(a),{isInWorker:!1,messagePort:d,canvas:this.j,runOnStartupFunctions:ma}),ra(this.U),this.Ma(),
this.ya=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.ya,a))}Na(a,d){this.Z();console.error(`[Preview] Failed to load project main script (${a}): `,d);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ma(){this.Z()}Z(){const a=window.Gb;a&&(a.parentElement.removeChild(a),window.Gb=null)}async sb(){const a=await sa(this.P);return{outputPort:a,transferables:[a]}}ob(){if(this.o)throw Error("not available in worker mode");
return this.ya}ka(a,d,c,e,f){this.S.postMessage({type:"event",component:a,handler:d,dispatchOpts:e||null,data:c,responseId:null},f)}eb(a,d){const c=la++,e=new Promise((f,g)=>{F.set(c,{resolve:f,reject:g})});this.S.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:d,responseId:c},void 0);return e}_OnMessageFromRuntime(a){const d=a.type;if("event"===d)return this.tb(a);if("result"===d)this.wb(a);else if("runtime-ready"===d)this.xb();else if("alert-error"===d)this.Z(),
alert(a.message);else if("creating-runtime"===d)this.Ma();else throw Error(`unknown message '${d}'`);}tb(a){const d=a.component,c=a.handler,e=a.data,f=a.responseId;if(a=E.get(d))if(a=a.get(c)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${d}' handler '${c}':`,h);null!==f&&this.Y(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Y(f,!0,h)).catch(h=>{console.error(`Rejection from '${d}' handler '${c}':`,h);this.Y(f,!1,""+h)}):this.Y(f,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${d}'`);
else console.warn(`[DOM] No event handlers for component '${d}'`)}Y(a,d,c){let e;c&&c.transferables&&(e=c.transferables);this.S.postMessage({type:"result",responseId:a,isOk:d,result:c},e)}wb(a){const d=a.responseId,c=a.isOk;a=a.result;const e=F.get(d);c?e.resolve(a):e.reject(a);F.delete(d)}g(a,d,c){let e=E.get(a);e||(e=new Map,E.set(a,e));if(e.has(d))throw Error(`[DOM] Component '${a}' already has handler '${d}'`);e.set(d,c)}static fa(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Ja(){for(const a of this.aa)if("runtime"===
a.N){this.U=a;return}throw Error("cannot find runtime DOM handler");}ub(a){this.ka("debugger","message",a)}xb(){for(const a of this.aa)a.Ea()}static K(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||oa)}static Oa(a){oa=!!a}gb(a){this.Ba.push(a);this.pa()}pa(){-1===this.F&&this.Ba.length&&(this.F=requestAnimationFrame(this.Eb))}ib(){-1!==this.F&&(cancelAnimationFrame(this.F),this.F=-1)}vb(){this.F=-1;for(const a of this.Ba)a();this.pa()}oa(){this.U.oa()}fb(){this.Ua=
!0}Za(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}ab(a){return!this.Za(a)}async D(a){return"cordova"===this.h&&(a.startsWith("file:")||this.va&&this.ab(a))?(a.startsWith(this.m)&&(a=a.substr(this.m.length)),a=await this.ga(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async rb(a){const d=a.filename;switch(a.as){case "text":return await this.Ya(d);case "buffer":return await this.ga(d);default:throw Error("unsupported type");}}Fa(a){const d=
window.cordova.file.applicationDirectory+"www/"+a;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(d,f=>{f.file(c,e)},e)})}async Ya(a){a=await this.Fa(a);return await ja(a)}la(){if(B.length&&!(8<=C)){C++;var a=B.shift();this.lb(a.filename,a.Ob,a.Hb)}}ga(a){return new Promise((d,c)=>{B.push({filename:a,Ob:e=>{C--;this.la();d(e)},Hb:e=>{C--;this.la();c(e)}});this.la()})}async lb(a,d,c){try{const e=await this.Fa(a),f=await ka(e);d(f)}catch(e){c(e)}}zb(){var a={type:"ready"};if("windows-webview2"===
this.h)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.h)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async kb(){const a=[];for(const [d,c]of Object.entries(this.A))a.push(this.jb(d,c));await Promise.all(a)}async jb(a,d){if("object"===typeof d)this.A[a]=new Blob([d.str],{type:d.type}),this.ba[a]=d.str;else{let c=await this.nb(d);c||(c=this.mb(d));this.A[a]=c}}async nb(a){try{return await (await fetch(a)).blob()}catch(d){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
d),null}}mb(a){a=this.yb(a);return this.hb(a.data,a.Kb)}yb(a){var d=a.indexOf(",");if(0>d)throw new URIError("expected comma in data: uri");var c=a.substring(d+1);d=a.substring(5,d).split(";");a=d[0]||"";const e=d[2];c="base64"===d[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Kb:a,data:c}}hb(a,d){var c=a.length;let e=c>>2,f=new Uint8Array(c),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=
3;c--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:d})}};"use strict";const G=self.X;function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,d)=>{const c=document.createElement("link");c.onload=()=>a(c);c.onerror=e=>d(e);c.rel="stylesheet";c.href=b;document.head.appendChild(c)})}function xa(b){return new Promise((a,d)=>{const c=new Image;c.onload=()=>a(c);c.onerror=e=>d(e);c.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,d)=>{let c=new FileReader;c.onload=e=>a(e.target.result);c.onerror=e=>d(e);c.readAsText(b)})}
async function za(b,a,d){if(!/firefox/i.test(navigator.userAgent))return await J(b);var c=await ya(b);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",d+"px");c=(new XMLSerializer).serializeToString(c);b=new Blob([c],{type:"image/svg+xml"});return await J(b)}
function K(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,d,c,e){b=await za(b,a,d);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(b,0,0,a,d);return f};
let N=!1;document.addEventListener("pause",()=>N=!0);document.addEventListener("resume",()=>N=!1);function ra(b){b.Sa=!0;b.xa=b.i.v();b.R=b.i.u()}async function Ia(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ja(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ka(b){return await self.C3_GetSvgImageSize(b.blob)}function La(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Ma(b){self.setTimeout(()=>{b.Ra=!0},1E3);"cordova"===b.i.h?(document.addEventListener("pause",()=>O(b,!0)),document.addEventListener("resume",()=>O(b,!1))):document.addEventListener("visibilitychange",()=>O(b,document.hidden));return{isSuspended:!(!document.hidden&&!N)}}
function Na(b){b.Qa||(b.Qa=!0,window.addEventListener("deviceorientation",a=>{b.l||l(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.l||l(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Oa(b){b.Pa||(b.Pa=!0,window.addEventListener("devicemotion",a=>{if(!b.l){var d=null,c=a.acceleration;c&&(d={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=a.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});l(b,"devicemotion",{acceleration:d,accelerationIncludingGravity:c,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Pa(b){await wa(b.url)}
function Qa(b,a){b.Ta=a.message;-1===b.sa&&(b.sa=setTimeout(()=>{b.sa=-1;const d=document.getElementById("exportToVideoMessage");d&&(d.textContent=b.Ta)},250))}function P(b){if(!b.l){var a=G.K();a&&"any"!==b.Ca&&Ra(b);l(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.v(),innerHeight:b.u()})}}function Q(b,a){console.warn("[Construct] Fullscreen request failed: ",a);l(b,"fullscreenerror",{isFullscreen:G.K(),innerWidth:b.v(),innerHeight:b.u()})}
function O(b,a){a?b.i.ib():b.i.pa();l(b,"visibilitychange",{hidden:a})}function Sa(b,a,d){"Backspace"===d.key&&M(d);if(!b.l){var c=ua.get(d.code)||d.code;p(b,a,{code:c,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},H)}}
function R(b,a,d,c){b.l||ta(d)||p(b,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,timeStamp:d.timeStamp},c)}function S(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function T(b,a,d){if(!b.l){var c=0;"mouse"===d.pointerType&&(c=b.T);p(b,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},H);"mouse"===d.pointerType&&(c="mousemove",
"pointerdown"===a?c="mousedown":"pointerup"===a&&(c="mouseup"),R(b,c,d,va),b.T=d.buttons)}}
function U(b,a,d){if(!b.l&&!ta(d)){var c=b.T;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");p(b,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,lastButtons:c,clientX:d.clientX,clientY:d.clientY+b.s,pageX:d.pageX,pageY:d.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},H);b.T=d.buttons;R(b,d.type,d,va)}}
function V(b,a,d){if(!b.l)for(let c=0,e=d.changedTouches.length;c<e;++c){const f=d.changedTouches[c];p(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.s,pageX:f.pageX,pageY:f.pageY+b.s,movementX:d.movementX||0,movementY:d.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:d.timeStamp},
H)}}function W(b,a,d){document.body.style.transform="";b.s=0;if(0<d){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),a=(c.top+c.bottom)/2-(a-d)/2,a>d&&(a=d),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.s=a))}}function Ua(b,a,d,c){const e=b.v(),f=b.u();b.H=-1;e!=a||f!=d?l(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.K()}):10>c&&Va(b,e,f,c+1)}
function Va(b,a,d,c){-1!==b.H&&clearTimeout(b.H);b.H=setTimeout(()=>Ua(b,a,d,c),48)}
function Ra(b){b=b.Ca;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",a)}}
function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.fa(class extends self.Ha{constructor(b){super(b,"runtime");this.Va=!0;this.Sa=!1;this.H=-1;this.Ca="any";this.Pa=this.Qa=!1;this.ca=document.createElement("div");this.ca.className="c3-screen-reader-text";this.ca.setAttribute("aria-live","polite");document.body.appendChild(this.ca);this.C=null;this.l=!1;this.Ta="";this.sa=-1;this.Ra=!1;this.xa=b.v();this.R=b.u();this.s=this.V=0;b.g("canvas","update-size",c=>{var e=this.i;e.Ua||(e=e.j,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+"px",
e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",c.displayScale),this.Va&&(e.style.display="",this.Va=!1))});b.g("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),g=document.body;f.textContent=c;f.href=e;f.download=c;g.appendChild(f);f.click();g.removeChild(f)});b.g("runtime","load-webfonts",c=>Ia(c));b.g("runtime","raster-svg-image",c=>Ja(c));b.g("runtime","get-svg-image-size",
c=>Ka(c));b.g("runtime","set-target-orientation",c=>{this.Ca=c.targetOrientation});b.g("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.g("runtime","post-to-debugger",c=>La(c));b.g("runtime","go-to-script",c=>La(c));b.g("runtime","before-start-ticking",()=>Ma(this));b.g("runtime","debug-highlight",c=>{if(c.show){this.C||(this.C=document.createElement("div"),this.C.id="inspectOutline",document.body.appendChild(this.C));var e=this.C;e.style.display="";e.style.left=c.left-
1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.C&&(this.C.style.display="none")});b.g("runtime","enable-device-orientation",()=>Na(this));b.g("runtime","enable-device-motion",()=>Oa(this));b.g("runtime","add-stylesheet",c=>Pa(c));b.g("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});b.g("runtime","alert",c=>{alert(c.message)});b.g("runtime",
"screen-reader-text",c=>{var e=c.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+c.id,e.textContent=c.text,this.ca.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+c.id))?e.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===e?(e=document.getElementById("c3-sr-"+c.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
b.g("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.g("runtime","set-exporting-to-video",c=>{this.l=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.i.j.style.display="";this.i.fb()});b.g("runtime","export-to-video-progress",c=>Qa(this,c));b.g("runtime","exported-to-video",c=>{window.Fb({type:"exported-video",
arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.g("runtime","exported-to-image-sequence",c=>{window.Fb({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;a.has(e.tagName.toLowerCase())||K(e)||c.preventDefault()});const d=b.j;window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);d.addEventListener("selectstart",M);d.addEventListener("gesturehold",
M);window.addEventListener("touchstart",M,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",M,{passive:!1}),d.addEventListener("pointerdown",M)):d.addEventListener("touchstart",M);this.T=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Fa,{passive:!1});window.addEventListener("wheel",Fa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.l&&this.Sa){var c=this.v();var e=this.u();if(this.i.Ia()){if(this.Ra){if(this.xa===
c&&e<this.R){this.V=this.R-e;W(this,this.R,this.V);c=void 0;break a}0<this.V&&(this.V=0,W(this,e,this.V))}this.xa=c;this.R=e}l(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.K()});this.i.ja()&&(-1!==this.H&&clearTimeout(this.H),Ua(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>P(this));window.addEventListener("webkitfullscreenchange",()=>P(this));window.addEventListener("mozfullscreenchange",()=>P(this));window.addEventListener("fullscreenerror",
c=>Q(this,c));window.addEventListener("webkitfullscreenerror",c=>Q(this,c));window.addEventListener("mozfullscreenerror",c=>Q(this,c));if(b.ja())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):K(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===c?(G.Oa(!0),P(this)):"exited-fullscreen"===c?(G.Oa(!1),P(this)):console.warn("Unknown wrapper message: ",c)};this.za=new Set;this.Db=new WeakSet;this.Bb=!1}Ea(){window.addEventListener("focus",()=>{l(this,"window-focus",null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(d){a=
!1}l(this,"window-blur",{parentHasFocus:a},I);this.T=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||K(a))&&l(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Sa(this,"keydown",a));window.addEventListener("keyup",a=>Sa(this,"keyup",a));window.addEventListener("dblclick",a=>R(this,"dblclick",a,H));window.addEventListener("wheel",a=>{this.l||l(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.s,pageX:a.pageX,pageY:a.pageY+this.s,deltaX:a.deltaX,
deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{S(a);T(this,"pointerdown",a)}),this.i.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{T(this,"pointermove",a)}):window.addEventListener("pointermove",a=>T(this,"pointermove",a)),window.addEventListener("pointerup",a=>T(this,"pointerup",a)),window.addEventListener("pointercancel",
a=>T(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{S(a);U(this,"pointerdown",a)}),window.addEventListener("mousemove",a=>U(this,"pointermove",a)),window.addEventListener("mouseup",a=>U(this,"pointerup",a)),window.addEventListener("touchstart",a=>{S(a);V(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>V(this,"pointermove",a)),window.addEventListener("touchend",a=>V(this,"pointerup",a)),window.addEventListener("touchcancel",a=>V(this,"pointercancel",a)));const b=
()=>this.oa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.i.$a()&&!this.i.Ia()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{W(this,this.u(),navigator.virtualKeyboard.boundingRect.height)}))}v(){return this.i.v()}u(){return this.i.u()}oa(){var b=
[...this.za];this.za.clear();if(!this.Bb)for(const a of b)(b=a.play())&&b.catch(()=>{this.Db.has(a)||this.za.add(a)})}});"use strict";async function pa(b){if(b.Ab)throw Error("already initialised");b.Ab=!0;var a=b.B.na(("playable-ad"===b.B.h?b.B.G:"")+"dispatchworker.js");b.qa=await b.B.ia(a,b.M,{name:"DispatchWorker"});a=new MessageChannel;b.ua=a.port1;b.qa.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Aa=await sa(b)}function qa(b){return[b.ua,b.Aa]}
async function sa(b){const a=b.Wa.length;var d=b.B.na(("playable-ad"===b.B.h?b.B.G:"")+"jobworker.js");d=await b.B.ia(d,b.M,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;b.qa.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);d.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);b.Wa.push(d);return e.port1}
self.cb=class{constructor(b){this.B=b;this.M=b.m;this.M="preview"===b.h?this.M+"workers/":this.M+b.G;this.Cb=Math.min(navigator.hardwareConcurrency||2,16);this.qa=null;this.Wa=[];this.Aa=this.ua=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.X({Pb:!0,Qb:"workermain.js",J:["scripts/c3runtime.js"],da:[],Da:"",Mb:"scripts/",ea:[],Xa:"html5"}));"use strict";function Y(b){b.stopPropagation()}function Wa(b){13!==b.which&&27!==b.which&&b.stopPropagation()}
self.X.fa(class extends self.Ga{constructor(b){super(b,"text-input");t(this,"scroll-to-bottom",a=>{a.scrollTop=a.scrollHeight})}ha(b,a){let d;const c=a.type;"textarea"===c?(d=document.createElement("textarea"),d.style.resize="none"):(d=document.createElement("input"),d.type=c);d.style.position="absolute";d.autocomplete="off";d.addEventListener("pointerdown",Y);d.addEventListener("pointermove",Y);d.addEventListener("pointerrawupdate",Y);d.addEventListener("pointerup",Y);d.addEventListener("mousedown",
Y);d.addEventListener("mouseup",Y);d.addEventListener("keydown",Wa);d.addEventListener("keyup",Wa);d.addEventListener("click",e=>{e.stopPropagation();v(this,"click",b)});d.addEventListener("dblclick",e=>{e.stopPropagation();v(this,"dblclick",b)});d.addEventListener("input",()=>r(this,"change",b,{text:d.value}));a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.L(d,a);return d}L(b,a){b.value=a.text;b.placeholder=a.placeholder;b.title=a.title;b.disabled=!a.isEnabled;b.readOnly=a.isReadOnly;
b.spellcheck=a.spellCheck;a=a.maxLength;0>a?b.removeAttribute("maxlength"):b.setAttribute("maxlength",a)}});"use strict";function Z(b){b.stopPropagation()}
self.X.fa(class extends self.Ga{constructor(b){super(b,"button")}ha(b,a){const d=document.createElement("input");var c=d;a.isCheckbox?(d.type="checkbox",c=document.createElement("label"),c.appendChild(d),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):d.type="button";c.style.position="absolute";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",
Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);d.addEventListener("click",()=>v(this,"click",b,{isChecked:d.checked}));a.id&&(d.id=a.id);a.className&&(d.className=a.className);this.L(c,a);return c}ma(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}L(b,a){const d="input"===b.tagName.toLowerCase()?b:b.firstChild;d.checked=a.isChecked;
d.disabled=!a.isEnabled;b.title=a.title;b===d?d.value=a.text:b.lastChild.textContent=a.text}});
