function p(d,b,a,c){d.s.Ga(d.aa,b,a,c,void 0)}function w(d,b,a,c){d.s.C?p(d,b,a,c):d.s.Xb()._OnMessageFromDOM({type:"event",component:d.aa,handler:b,dispatchOpts:c||null,data:a,responseId:null})}function x(d,b,a){d.s.j(d.aa,b,a)}function aa(d,b){for(const [a,c]of b)x(d,a,c)}window.ma=class{constructor(d,b){this.s=d;this.aa=b}gb(){}};window.cd=class{constructor(){}};"use strict";class ba{constructor(d){this.Oa=d;this.Qa=!1;this.Ta=!0}}
function ca(d,b){const a=b.elementId,c=d.Aa(a,b),e=new ba(c);d.ba.set(a,e);c.style.boxSizing="border-box";c.style.display="none";e.Ta=!!b.isVisible;b=d.Ja(c);b.addEventListener("focus",()=>{y(d,"elem-focused",a)});b.addEventListener("blur",()=>{y(d,"elem-blurred",a)});d.qa&&document.body.appendChild(c)}function da(d,b,a){x(d,b,c=>{const e=A(d,c.elementId);return a(e,c)})}function A(d,b){d=d.ba.get(b);if(!d)throw Error(`no element with id ${b}`);return d.Oa}
function y(d,b,a,c){c||(c={});c.elementId=a;p(d,b,c)}function B(d,b,a,c){c||(c={});c.elementId=a;w(d,b,c)}
window.ib=class extends self.ma{constructor(d,b){super(d,b);this.ba=new Map;this.qa=!0;aa(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const c=A(this,a);this.qa&&c.parentElement.removeChild(c);this.ba.delete(a)}],["set-visible",a=>{if(this.qa){var c=this.ba.get(a.elementId),e=c.Oa;c.Qa?e.style.display=a.isVisible?"":"none":c.Ta=!!a.isVisible}}],["update-position",a=>{if(this.qa){var c=this.ba.get(a.elementId),e=c.Oa;e.style.left=a.left+"px";e.style.top=a.top+"px";e.style.width=a.width+
"px";e.style.height=a.height+"px";a=a.fontSize;null!==a&&(e.style.fontSize=a+"em");c.Qa||(c.Qa=!0,c.Ta&&(e.style.display=""))}}],["update-state",a=>{const c=A(this,a.elementId);this.Y(c,a)}],["focus",a=>{const c=this.Ja(A(this,a.elementId));a.focus?c.focus():c.blur()}],["set-css-style",a=>{const c=A(this,a.elementId),e=a.prop;a=a.val;e.startsWith("--")?c.style.setProperty(e,a):c.style[e]=a}],["set-attribute",a=>{A(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{A(this,a.elementId).removeAttribute(a.name)}]]);
da(this,"get-element",a=>a)}Aa(){throw Error("required override");}Y(){throw Error("required override");}Ja(d){return d}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),C=/android/i.test(navigator.userAgent),fa=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let ha=0;
function D(d){const b=document.createElement("script");b.async=!1;b.type="module";return d.Ic?new Promise(a=>{const c="c3_resolve_"+ha;++ha;self[c]=a;b.textContent=d.Vc+`\n\nself["${c}"]();`;document.head.appendChild(b)}):new Promise((a,c)=>{b.onload=a;b.onerror=c;b.src=d;document.head.appendChild(b)})}let ia=!1,ka=!1;function la(){if(!ia){try{new Worker("blob://",{get type(){ka=!0}})}catch(d){}ia=!0}return ka}let F=new Audio;
const na={"audio/webm; codecs=opus":!!F.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!F.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!F.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!F.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!F.canPlayType("audio/mp4"),"audio/mpeg":!!F.canPlayType("audio/mpeg")};F=null;async function oa(d){d=await pa(d);return(new TextDecoder("utf-8")).decode(d)}
function pa(d){return new Promise((b,a)=>{const c=new FileReader;c.onload=e=>b(e.target.result);c.onerror=e=>a(e);c.readAsArrayBuffer(d)})}const H=[];let I=0;window.RealFile=window.File;const J=[],L=new Map,M=new Map;let qa=0;const ra=[];self.runOnStartup=function(d){if("function"!==typeof d)throw Error("runOnStartup called without a function");ra.push(d)};const sa=new Set(["cordova","playable-ad","instant-games"]);let ta=!1;
window.O=class d{constructor(b){this.C=b.Xc;this.ea=null;this.B="";this.S=b.Sc;this.ia={};this.Va=this.U=null;this.ra=[];this.u=this.ga=null;this.xb=!1;this.ca=null;this.R=-1;this.oc=()=>this.dc();this.Ya=[];this.l=b.Db;this.Sa="file"===location.protocol.substr(0,4);!this.C||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&la()||(this.C=!1);this.C&&fa&&(this.C=!1);if("playable-ad"===this.l||"instant-games"===this.l)this.C=!1;if("cordova"===this.l&&this.C)if(C){const a=/Chrome\/(\d+)/i.exec(navigator.userAgent);
a&&90<=parseInt(a[1],10)||(this.C=!1)}else this.C=!1;this.sa=this.J=null;"html5"!==this.l||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.j("runtime","cordova-fetch-local-file",a=>this.$b(a));this.j("runtime","create-job-worker",()=>this.ac());"cordova"===this.l?document.addEventListener("deviceready",()=>this.ob(b)):this.ob(b)}Lb(){return ea&&
"cordova"===this.l}Fa(){const b=navigator.userAgent;return ea&&sa.has(this.l)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(b)}Jb(){return C}jb(){return C&&sa.has(this.l)}async ob(b){"macos-wkwebview"===this.l&&this.ic();if("playable-ad"===this.l){this.J=self.c3_base64files;this.sa={};await this.Tb();for(let c=0,e=b.V.length;c<e;++c){var a=b.V[c];this.sa.hasOwnProperty(a)?b.V[c]={Ic:!0,Vc:this.sa[a]}:this.J.hasOwnProperty(a)&&(b.V[c]=URL.createObjectURL(this.J[a]))}b.ya=[]}if("nwjs"===this.l&&
self.nw&&self.nw.App.manifest["c3-steam-mode"]){let c=0;this.Pb(()=>{c++;document.body.style.opacity=0===c%2?"1":"0.999"})}b.Rc?this.B=b.Rc:(a=location.origin,this.B=("null"===a?"file:///":a)+location.pathname,a=this.B.lastIndexOf("/"),-1!==a&&(this.B=this.B.substr(0,a+1)));b.Zc&&(this.ia=b.Zc);a=new MessageChannel;this.ea=a.port1;this.ea.onmessage=c=>this._OnMessageFromRuntime(c.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.cc(c));this.ca=new self.Mb(this);await ua(this.ca);
"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((c,e)=>{window.AndroidFullScreen.immersiveMode(c,e)})}catch(c){console.error("Failed to enter Android immersive mode: ",c)}this.C?await this.Zb(b,a.port2):await this.Yb(b,a.port2)}Ka(b){b=this.ia.hasOwnProperty(b)?this.ia[b]:b.endsWith("/workermain.js")&&this.ia.hasOwnProperty("workermain.js")?this.ia["workermain.js"]:"playable-ad"===this.l&&this.J.hasOwnProperty(b)?this.J[b]:
b;b instanceof Blob&&(b=URL.createObjectURL(b));return b}async Ba(b,a,c){if(b.startsWith("blob:"))return new Worker(b,c);if("cordova"===this.l&&this.Sa)return b=await this.za(c.Hc?b:this.S+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),c);b=new URL(b,a);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");b=await b.blob();return new Worker(URL.createObjectURL(b),c)}return new Worker(b,c)}I(){return Math.max(window.innerWidth,
1)}G(){return Math.max(window.innerHeight,1)}nb(b){var a=this.B,c=location.href,e=this.I(),f=this.G(),h=window.devicePixelRatio,k=d.X(),l=b.Nd,m=window.cr_previewImageBlobs||this.J,g=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,E=window.od||"";b=b.Db;var Y=(new URLSearchParams(self.location.search)).has("debug"),v=this.ca;return{runtimeBaseUrl:a,previewUrl:c,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:g,
previewProjectFileSWUrls:t,swClientId:E,exportType:b,isDebug:Y,ife:!!self.Bd,jobScheduler:{inputPort:v.Ra,outputPort:v.Xa,maxNumWorkers:v.mc},supportedAudioFormats:na,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.S+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.S+"opus.wasm.wasm",isFileProtocol:this.Sa,isiOSCordova:this.Lb(),isiOSWebView:this.Fa(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Zb(b,a){const c=this.Ka(b.Yc);"preview"===this.l?(this.U=new Worker("previewworker.js",
{type:"module",name:"Runtime"}),await new Promise((k,l)=>{const m=g=>{this.U.removeEventListener("message",m);g.data&&"ok"===g.data.type?k():l()};this.U.addEventListener("message",m);this.U.postMessage({type:"construct-worker-init","import":(new URL(c,this.B)).toString()})})):this.U=await this.Ba(c,this.B,{type:"module",name:"Runtime",Hc:!0});this.u=document.createElement("canvas");this.u.style.display="none";const e=this.u.transferControlToOffscreen();document.body.appendChild(this.u);window.c3canvas=
this.u;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let f=b.ya||[],h=b.V;f=await Promise.all(f.map(k=>this.P(k)));h=await Promise.all(h.map(k=>this.P(k)));if("cordova"===this.l)for(let k=0,l=b.xa.length;k<l;++k){const m=b.xa[k],g=m[0];if(g===b.$a||"scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))m[1]=await this.P(g)}this.U.postMessage(Object.assign(this.nb(b),{type:"init-runtime",isInWorker:!0,messagePort:a,canvas:e,workerDependencyScripts:f,engineScripts:h,projectScripts:b.xa,
mainProjectScript:b.$a,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[a,e,...va(this.ca)]);this.ra=J.map(k=>new k(this));this.mb();wa(this.ga);self.c3_callFunction=(k,l)=>{var m=this.ga;return m.s.Nb(m.aa,{name:k,params:l})};"preview"===this.l&&(self.goToLastErrorScript=()=>this.Ga("runtime","go-to-last-error-script"))}async Yb(b,a){this.u=document.createElement("canvas");this.u.style.display="none";document.body.appendChild(this.u);window.c3canvas=this.u;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();
this.ra=J.map(h=>new h(this));this.mb();var c=b.V.map(h=>"string"===typeof h?(new URL(h,this.B)).toString():h);if(Array.isArray(b.ya)){var e=[...b.ya].map(h=>h instanceof Blob?URL.createObjectURL(h):h);c.unshift(...e)}c=await Promise.all(c.map(h=>this.P(h)));await Promise.all(c.map(h=>D(h)));c=self.C3_ProjectScriptsStatus;e=b.$a;const f=b.xa;for(let [h,k]of f)if(k||(k=h),h===e)try{k=await this.P(k),await D(k),"preview"!==this.l||c[h]||this.qb(h,"main script did not run to completion")}catch(l){this.qb(h,
l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.P(k),await D(k);"preview"===this.l&&"object"!==typeof self.$c.fd?(this.pa(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(b=Object.assign(this.nb(b),{isInWorker:!1,messagePort:a,canvas:this.u,runOnStartupFunctions:ra}),wa(this.ga),
this.pb(),this.Va=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.Va,b))}qb(b,a){this.pa();console.error(`[Preview] Failed to load project main script (${b}): `,a);alert(`Failed to load project main script (${b}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}pb(){this.pa()}pa(){const b=window.sc;b&&(b.parentElement.removeChild(b),window.sc=null)}async ac(){const b=await xa(this.ca);return{outputPort:b,transferables:[b]}}Xb(){if(this.C)throw Error("not available in worker mode");
return this.Va}Ga(b,a,c,e,f){this.ea.postMessage({type:"event",component:b,handler:a,dispatchOpts:e||null,data:c,responseId:null},f)}Nb(b,a){const c=qa++,e=new Promise((f,h)=>{M.set(c,{resolve:f,reject:h})});this.ea.postMessage({type:"event",component:b,handler:"js-invoke-function",dispatchOpts:null,data:a,responseId:c},void 0);return e}_OnMessageFromRuntime(b){const a=b.type;if("event"===a)return this.bc(b);if("result"===a)this.ec(b);else if("runtime-ready"===a)this.fc();else if("alert-error"===
a)this.pa(),alert(b.message);else if("creating-runtime"===a)this.pb();else throw Error(`unknown message '${a}'`);}bc(b){const a=b.component,c=b.handler,e=b.data,f=b.responseId;if(b=L.get(a))if(b=b.get(c)){var h=null;try{h=b(e)}catch(k){console.error(`Exception in '${a}' handler '${c}':`,k);null!==f&&this.oa(f,!1,""+k);return}if(null===f)return h;h&&h.then?h.then(k=>this.oa(f,!0,k)).catch(k=>{console.error(`Rejection from '${a}' handler '${c}':`,k);this.oa(f,!1,""+k)}):this.oa(f,!0,h)}else console.warn(`[DOM] No handler '${c}' for component '${a}'`);
else console.warn(`[DOM] No event handlers for component '${a}'`)}oa(b,a,c){let e;c&&c.transferables&&(e=c.transferables);this.ea.postMessage({type:"result",responseId:b,isOk:a,result:c},e)}ec(b){const a=b.responseId,c=b.isOk;b=b.result;const e=M.get(a);c?e.resolve(b):e.reject(b);M.delete(a)}j(b,a,c){let e=L.get(b);e||(e=new Map,L.set(b,e));if(e.has(a))throw Error(`[DOM] Component '${b}' already has handler '${a}'`);e.set(a,c)}static W(b){if(J.includes(b))throw Error("DOM handler already added");
J.push(b)}mb(){for(const b of this.ra)if("runtime"===b.aa){this.ga=b;return}throw Error("cannot find runtime DOM handler");}cc(b){this.Ga("debugger","message",b)}fc(){for(const b of this.ra)b.gb()}static X(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ta)}static rb(b){ta=!!b}Pb(b){this.Ya.push(b);this.Ma()}Ma(){-1===this.R&&this.Ya.length&&(this.R=requestAnimationFrame(this.oc))}Rb(){-1!==this.R&&(cancelAnimationFrame(this.R),this.R=-1)}dc(){this.R=
-1;for(const b of this.Ya)b();this.Ma()}La(){this.ga.La()}Ob(){this.xb=!0}Ib(b){return/^(?:[a-z\-]+:)?\/\//.test(b)||"data:"===b.substr(0,5)||"blob:"===b.substr(0,5)}Kb(b){return!this.Ib(b)}async P(b){return"cordova"===this.l&&(b.startsWith("file:")||this.Sa&&this.Kb(b))?(b.startsWith(this.B)&&(b=b.substr(this.B.length)),b=await this.za(b),URL.createObjectURL(new Blob([b],{type:"application/javascript"}))):b}async $b(b){const a=b.filename;switch(b.as){case "text":return await this.Hb(a);case "buffer":return await this.za(a);
default:throw Error("unsupported type");}}hb(b){const a=window.cordova.file.applicationDirectory+"www/"+b;return new Promise((c,e)=>{window.resolveLocalFileSystemURL(a,f=>{f.file(c,e)},e)})}async Hb(b){b=await this.hb(b);return await oa(b)}Ia(){if(H.length&&!(8<=I)){I++;var b=H.shift();this.Ub(b.filename,b.Wc,b.Bc)}}za(b){return new Promise((a,c)=>{H.push({filename:b,Wc:e=>{I--;this.Ia();a(e)},Bc:e=>{I--;this.Ia();c(e)}});this.Ia()})}async Ub(b,a,c){try{const e=await this.hb(b),f=await pa(e);a(f)}catch(e){c(e)}}ic(){var b=
{type:"ready"};if("windows-webview2"===this.l)window.chrome.webview.postMessage(JSON.stringify(b));else if("macos-wkwebview"===this.l)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(b));else throw Error("cannot send wrapper message");}async Tb(){const b=[];for(const [a,c]of Object.entries(this.J))b.push(this.Sb(a,c));await Promise.all(b)}async Sb(b,a){if("object"===typeof a)this.J[b]=new Blob([a.str],{type:a.type}),this.sa[b]=a.str;else{let c=await this.Wb(a);c||(c=this.Vb(a));
this.J[b]=c}}async Wb(b){try{return await (await fetch(b)).blob()}catch(a){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",a),null}}Vb(b){b=this.hc(b);return this.Qb(b.data,b.Jc)}hc(b){var a=b.indexOf(",");if(0>a)throw new URIError("expected comma in data: uri");var c=b.substring(a+1);a=b.substring(5,a).split(";");b=a[0]||"";const e=a[2];
c="base64"===a[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Jc:b,data:c}}Qb(b,a){var c=b.length;let e=c>>2,f=new Uint8Array(c),h=new Uint32Array(f.buffer,0,e),k,l;for(l=k=0;k<e;++k)h[k]=b.charCodeAt(l++)|b.charCodeAt(l++)<<8|b.charCodeAt(l++)<<16|b.charCodeAt(l++)<<24;for(c&=3;c--;)f[l]=b.charCodeAt(l),++l;return new Blob([f],{type:a})}};"use strict";const N=self.O;
function ya(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents}const za=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),P={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},Aa={dispatchUserScriptEvent:!0},R={dispatchRuntimeEvent:!0};
function Ba(d){return new Promise((b,a)=>{const c=document.createElement("link");c.onload=()=>b(c);c.onerror=e=>a(e);c.rel="stylesheet";c.href=d;document.head.appendChild(c)})}function Ca(d){return new Promise((b,a)=>{const c=new Image;c.onload=()=>b(c);c.onerror=e=>a(e);c.src=d})}async function S(d){d=URL.createObjectURL(d);try{return await Ca(d)}finally{URL.revokeObjectURL(d)}}
function Da(d){return new Promise((b,a)=>{let c=new FileReader;c.onload=e=>b(e.target.result);c.onerror=e=>a(e);c.readAsText(d)})}
async function Fa(d,b,a){if(!/firefox/i.test(navigator.userAgent))return await S(d);var c=await Da(d);c=(new DOMParser).parseFromString(c,"image/svg+xml");const e=c.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),h=e.getAttribute("height");if(!f.includes("%")&&!h.includes("%"))return await S(d)}e.setAttribute("width",b+"px");e.setAttribute("height",a+"px");c=(new XMLSerializer).serializeToString(c);d=new Blob([c],{type:"image/svg+xml"});return await S(d)}
function Ga(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;d=d.parentNode}while(d);return!1}const Ha=new Set(["input","textarea","datalist","select"]),Ia=new Set(["canvas","body","html"]);function T(d){d.target.tagName&&Ia.has(d.target.tagName.toLowerCase())&&d.preventDefault()}function Ja(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()}
self.C3_GetSvgImageSize=async function(d){d=await S(d);if(0<d.width&&0<d.height)return[d.width,d.height];d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const b=d.getBoundingClientRect();document.body.removeChild(d);return[b.width,b.height]};self.C3_RasterSvgImageBlob=async function(d,b,a,c,e){d=await Fa(d,b,a);const f=document.createElement("canvas");f.width=c;f.height=e;f.getContext("2d").drawImage(d,0,0,b,a);return f};
let Ka=!1;document.addEventListener("pause",()=>Ka=!0);document.addEventListener("resume",()=>Ka=!1);function wa(d){d.vb=!0;d.Ua=d.s.I();d.da=d.s.G()}async function La(d){await Promise.all(d.webfonts.map(async b=>{b=new FontFace(b.name,`url('${b.url}')`);document.fonts.add(b);await b.load()}))}
async function Ma(d){var b=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);b=b?await createImageBitmap(d,b):await createImageBitmap(d);return{imageBitmap:b,transferables:[b]}}async function Na(d){return await self.C3_GetSvgImageSize(d.blob)}function Oa(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}
function Pa(d){self.setTimeout(()=>{d.ub=!0},1E3);"cordova"===d.s.l?(document.addEventListener("pause",()=>Qa(d,!0)),document.addEventListener("resume",()=>Qa(d,!1))):document.addEventListener("visibilitychange",()=>Qa(d,document.hidden));return{isSuspended:!(!document.hidden&&!Ka)}}
function Ra(d){d.tb||(d.tb=!0,window.addEventListener("deviceorientation",b=>{d.A||p(d,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},P)}),window.addEventListener("deviceorientationabsolute",b=>{d.A||p(d,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},P)}))}
function Sa(d){d.sb||(d.sb=!0,window.addEventListener("devicemotion",b=>{if(!d.A){var a=null,c=b.acceleration;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var e=b.accelerationIncludingGravity;e&&(c={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=b.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});p(d,"devicemotion",{acceleration:a,accelerationIncludingGravity:c,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},P)}}))}async function Ta(d){await Ba(d.url)}
function Ua(d,b){d.wb=b.message;-1===d.Pa&&(d.Pa=setTimeout(()=>{d.Pa=-1;const a=document.getElementById("exportToVideoMessage");a&&(a.textContent=d.wb)},250))}function U(d){if(!d.A){var b=N.X();b&&"any"!==d.Za&&Va(d);p(d,"fullscreenchange",{isFullscreen:b,innerWidth:d.I(),innerHeight:d.G()})}}function Wa(d,b){console.warn("[Construct] Fullscreen request failed: ",b);p(d,"fullscreenerror",{isFullscreen:N.X(),innerWidth:d.I(),innerHeight:d.G()})}
function Qa(d,b){b?d.s.Rb():d.s.Ma();p(d,"visibilitychange",{hidden:b})}function Xa(d,b,a){"Backspace"===a.key&&T(a);if(!d.A){var c=za.get(a.code)||a.code;w(d,b,{code:c,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},P)}}
function Ya(d,b,a,c){d.A||ya(a)||w(d,b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY+d.D,pageX:a.pageX,pageY:a.pageY+d.D,movementX:a.movementX||0,movementY:a.movementY||0,timeStamp:a.timeStamp},c)}function Za(d){window!==window.top&&window.focus();$a(d.target)&&document.activeElement&&!$a(document.activeElement)&&document.activeElement.blur()}
function V(d,b,a){if(!d.A){var c=0;"mouse"===a.pointerType&&(c=d.fa);w(d,b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY+d.D,pageX:a.pageX,pageY:a.pageY+d.D,movementX:a.movementX||0,movementY:a.movementY||0,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},P);"mouse"===a.pointerType&&(c=
"mousemove","pointerdown"===b?c="mousedown":"pointerup"===b&&(c="mouseup"),Ya(d,c,a,Aa),d.fa=a.buttons)}}
function ab(d,b,a){if(!d.A&&!ya(a)){var c=d.fa;"pointerdown"===b&&0!==c?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");w(d,b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,clientY:a.clientY+d.D,pageX:a.pageX,pageY:a.pageY+d.D,movementX:a.movementX||0,movementY:a.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},P);d.fa=a.buttons;Ya(d,a.type,a,Aa)}}
function W(d,b,a){if(!d.A)for(let c=0,e=a.changedTouches.length;c<e;++c){const f=a.changedTouches[c];w(d,b,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+d.D,pageX:f.pageX,pageY:f.pageY+d.D,movementX:a.movementX||0,movementY:a.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:a.timeStamp},
P)}}function bb(d,b,a){document.body.style.transform="";d.D=0;if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`,d.D=b))}}function cb(d,b,a,c){const e=d.I(),f=d.G();d.T=-1;e!=b||f!=a?p(d,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.X()}):10>c&&db(d,e,f,c+1)}
function db(d,b,a,c){-1!==d.T&&clearTimeout(d.T);d.T=setTimeout(()=>cb(d,b,a,c),48)}
function Va(d){d=d.Za;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(b=>console.warn("[Construct] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(d):screen.webkitLockOrientation?b=screen.webkitLockOrientation(d):screen.mozLockOrientation?b=screen.mozLockOrientation(d):screen.msLockOrientation&&(b=screen.msLockOrientation(d));b||console.warn("[Construct] Failed to lock orientation")}catch(b){console.warn("[Construct] Failed to lock orientation: ",b)}}
function $a(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}
N.W(class extends self.ma{constructor(d){super(d,"runtime");this.yb=!0;this.vb=!1;this.T=-1;this.Za="any";this.sb=this.tb=!1;this.ta=document.createElement("div");this.ta.className="c3-screen-reader-text";this.ta.setAttribute("aria-live","polite");document.body.appendChild(this.ta);this.N=null;this.A=!1;this.wb="";this.Pa=-1;this.ub=!1;this.Ua=d.I();this.da=d.G();this.D=this.ha=0;d.j("canvas","update-size",c=>{var e=this.s;e.xb||(e=e.u,e.style.width=c.styleWidth+"px",e.style.height=c.styleHeight+
"px",e.style.marginLeft=c.marginLeft+"px",e.style.marginTop=c.marginTop+"px",document.documentElement.style.setProperty("--construct-scale",c.displayScale),this.yb&&(e.style.display="",this.yb=!1))});d.j("runtime","invoke-download",c=>{const e=c.url;c=c.filename;const f=document.createElement("a"),h=document.body;f.textContent=c;f.href=e;f.download=c;h.appendChild(f);f.click();h.removeChild(f)});d.j("runtime","load-webfonts",c=>La(c));d.j("runtime","raster-svg-image",c=>Ma(c));d.j("runtime","get-svg-image-size",
c=>Na(c));d.j("runtime","set-target-orientation",c=>{this.Za=c.targetOrientation});d.j("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});d.j("runtime","post-to-debugger",c=>Oa(c));d.j("runtime","go-to-script",c=>Oa(c));d.j("runtime","before-start-ticking",()=>Pa(this));d.j("runtime","debug-highlight",c=>{if(c.show){this.N||(this.N=document.createElement("div"),this.N.id="inspectOutline",document.body.appendChild(this.N));var e=this.N;e.style.display="";e.style.left=c.left-
1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.N&&(this.N.style.display="none")});d.j("runtime","enable-device-orientation",()=>Ra(this));d.j("runtime","enable-device-motion",()=>Sa(this));d.j("runtime","add-stylesheet",c=>Ta(c));d.j("runtime","script-create-worker",c=>{const e=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:e},[e])});d.j("runtime","alert",c=>{alert(c.message)});d.j("runtime",
"screen-reader-text",c=>{var e=c.type;"create"===e?(e=document.createElement("p"),e.id="c3-sr-"+c.id,e.textContent=c.text,this.ta.appendChild(e)):"update"===e?(e=document.getElementById("c3-sr-"+c.id))?e.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===e?(e=document.getElementById("c3-sr-"+c.id))?e.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${e}'`)});
d.j("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});d.j("runtime","set-exporting-to-video",c=>{this.A=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=c.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.s.u.style.display="";this.s.Ob()});d.j("runtime","export-to-video-progress",c=>Ua(this,c));d.j("runtime","exported-to-video",c=>{window.rc({type:"exported-video",
arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});d.j("runtime","exported-to-image-sequence",c=>{window.rc({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const e=c.target;b.has(e.tagName.toLowerCase())||Ga(e)||c.preventDefault()});const a=d.u;window.addEventListener("selectstart",T);window.addEventListener("gesturehold",T);a.addEventListener("selectstart",T);a.addEventListener("gesturehold",
T);window.addEventListener("touchstart",T,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",T,{passive:!1}),a.addEventListener("pointerdown",T)):a.addEventListener("touchstart",T);this.fa=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ja,{passive:!1});window.addEventListener("wheel",Ja,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.A&&this.vb){var c=this.I();var e=this.G();if(this.s.jb()){if(this.ub){if(this.Ua===
c&&e<this.da){this.ha=this.da-e;bb(this,this.da,this.ha);c=void 0;break a}0<this.ha&&(this.ha=0,bb(this,e,this.ha))}this.Ua=c;this.da=e}p(this,"window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.X()});this.s.Fa()&&(-1!==this.T&&clearTimeout(this.T),cb(this,c,e,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>U(this));window.addEventListener("webkitfullscreenchange",()=>U(this));window.addEventListener("mozfullscreenchange",()=>
U(this));window.addEventListener("fullscreenerror",c=>Wa(this,c));window.addEventListener("webkitfullscreenerror",c=>Wa(this,c));window.addEventListener("mozfullscreenerror",c=>Wa(this,c));if(d.Fa())if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>c&&(document.scrollingElement.scrollTop=0);c=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;if(f){var c=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));
c="textarea"===c?!0:"input"===c?e.has(f.type.toLowerCase()||"text"):Ga(f)}else c=!1}c||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=c=>{"entered-fullscreen"===c?(N.rb(!0),U(this)):"exited-fullscreen"===c?(N.rb(!1),U(this)):console.warn("Unknown wrapper message: ",c)};this.Wa=new Set;this.nc=new WeakSet;this.lc=!1}gb(){window.addEventListener("focus",()=>{p(this,"window-focus",null,R)});window.addEventListener("blur",()=>{try{var b=window.parent&&window.parent.document.hasFocus()}catch(a){b=
!1}p(this,"window-blur",{parentHasFocus:b},R);this.fa=0});window.addEventListener("focusin",b=>{b=b.target;(Ha.has(b.tagName.toLowerCase())||Ga(b))&&p(this,"keyboard-blur",null,R)});window.addEventListener("keydown",b=>Xa(this,"keydown",b));window.addEventListener("keyup",b=>Xa(this,"keyup",b));window.addEventListener("dblclick",b=>Ya(this,"dblclick",b,P));window.addEventListener("wheel",b=>{this.A||p(this,"wheel",{clientX:b.clientX,clientY:b.clientY+this.D,pageX:b.pageX,pageY:b.pageY+this.D,deltaX:b.deltaX,
deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},P)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{Za(b);V(this,"pointerdown",b)}),this.s.C&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",b=>{V(this,"pointermove",b)}):window.addEventListener("pointermove",b=>V(this,"pointermove",b)),window.addEventListener("pointerup",b=>V(this,"pointerup",b)),window.addEventListener("pointercancel",
b=>V(this,"pointercancel",b))):(window.addEventListener("mousedown",b=>{Za(b);ab(this,"pointerdown",b)}),window.addEventListener("mousemove",b=>ab(this,"pointermove",b)),window.addEventListener("mouseup",b=>ab(this,"pointerup",b)),window.addEventListener("touchstart",b=>{Za(b);W(this,"pointerdown",b)}),window.addEventListener("touchmove",b=>W(this,"pointermove",b)),window.addEventListener("touchend",b=>W(this,"pointerup",b)),window.addEventListener("touchcancel",b=>W(this,"pointercancel",b)));const d=
()=>this.La();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0);this.s.Jb()&&!this.s.jb()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{bb(this,this.G(),navigator.virtualKeyboard.boundingRect.height)}))}I(){return this.s.I()}G(){return this.s.G()}La(){var d=
[...this.Wa];this.Wa.clear();if(!this.lc)for(const b of d)(d=b.play())&&d.catch(()=>{this.nc.has(b)||this.Wa.add(b)})}});"use strict";async function ua(d){if(d.jc)throw Error("already initialised");d.jc=!0;var b=d.M.Ka(("playable-ad"===d.M.l?d.M.S:"")+"dispatchworker.js");d.Na=await d.M.Ba(b,d.$,{name:"DispatchWorker"});b=new MessageChannel;d.Ra=b.port1;d.Na.postMessage({type:"_init","in-port":b.port2},[b.port2]);d.Xa=await xa(d)}function va(d){return[d.Ra,d.Xa]}
async function xa(d){const b=d.zb.length;var a=d.M.Ka(("playable-ad"===d.M.l?d.M.S:"")+"jobworker.js");a=await d.M.Ba(a,d.$,{name:"JobWorker"+b});const c=new MessageChannel,e=new MessageChannel;d.Na.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);a.postMessage({type:"init",number:b,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);d.zb.push(a);return e.port1}
self.Mb=class{constructor(d){this.M=d;this.$=d.B;this.$="preview"===d.l?this.$+"workers/":this.$+d.S;this.mc=Math.min(navigator.hardwareConcurrency||2,16);this.Na=null;this.zb=[];this.Xa=this.Ra=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.O({Xc:!0,Yc:"workermain.js",V:["scripts/c3runtime.js"],xa:[],$a:"",Sc:"scripts/",ya:[],Db:"html5"}));"use strict";function X(d){d.stopPropagation()}function eb(d){13!==d.which&&27!==d.which&&d.stopPropagation()}
self.O.W(class extends self.ib{constructor(d){super(d,"text-input");da(this,"scroll-to-bottom",b=>{b.scrollTop=b.scrollHeight})}Aa(d,b){let a;const c=b.type;"textarea"===c?(a=document.createElement("textarea"),a.style.resize="none"):(a=document.createElement("input"),a.type=c);a.style.position="absolute";a.autocomplete="off";a.addEventListener("pointerdown",X);a.addEventListener("pointermove",X);a.addEventListener("pointerrawupdate",X);a.addEventListener("pointerup",X);a.addEventListener("mousedown",
X);a.addEventListener("mouseup",X);a.addEventListener("keydown",eb);a.addEventListener("keyup",eb);a.addEventListener("click",e=>{e.stopPropagation();B(this,"click",d)});a.addEventListener("dblclick",e=>{e.stopPropagation();B(this,"dblclick",d)});a.addEventListener("input",()=>y(this,"change",d,{text:a.value}));b.id&&(a.id=b.id);b.className&&(a.className=b.className);this.Y(a,b);return a}Y(d,b){d.value=b.text;d.placeholder=b.placeholder;d.title=b.title;d.disabled=!b.isEnabled;d.readOnly=b.isReadOnly;
d.spellcheck=b.spellCheck;b=b.maxLength;0>b?d.removeAttribute("maxlength"):d.setAttribute("maxlength",b)}});"use strict";function Z(d){d.stopPropagation()}
self.O.W(class extends self.ib{constructor(d){super(d,"button")}Aa(d,b){const a=document.createElement("input");var c=a;b.isCheckbox?(a.type="checkbox",c=document.createElement("label"),c.appendChild(a),c.appendChild(document.createTextNode("")),c.style.fontFamily="sans-serif",c.style.userSelect="none",c.style.webkitUserSelect="none",c.style.display="inline-block",c.style.color="black"):a.type="button";c.style.position="absolute";c.addEventListener("pointerdown",Z);c.addEventListener("pointermove",
Z);c.addEventListener("pointerrawupdate",Z);c.addEventListener("pointerup",Z);c.addEventListener("mousedown",Z);c.addEventListener("mouseup",Z);c.addEventListener("keydown",Z);c.addEventListener("keyup",Z);a.addEventListener("click",()=>B(this,"click",d,{isChecked:a.checked}));b.id&&(a.id=b.id);b.className&&(a.className=b.className);this.Y(c,b);return c}Ja(d){return"input"===d.tagName.toLowerCase()?d:d.firstChild}Y(d,b){const a="input"===d.tagName.toLowerCase()?d:d.firstChild;a.checked=b.isChecked;
a.disabled=!b.isEnabled;d.title=b.title;d===a?a.value=b.text:d.lastChild.textContent=b.text}});"use strict";
self.O.W(class extends self.ma{constructor(d){super(d,"sparsha_firebase_sdk");var b=this;x(this,"domSync_sparsha_fSDK",function(a){function c(){p(b,"run_sparsha_fSDK"+a.wa,e)}var e={action:a.action,status:"none",ka:{},la:{}},f=globalThis.Gb;if("init"===a.action||"reconnect"===a.action){function fb(){var q={},r={},Q=f.bb[a.g];1===f.Ab[a.g]&&"reconnect"!==a.action||f.h.Ld(Q,u=>{var G=f.na(u,a.g);q=G.ua;r=G.va;u?a.debug&&console.log("LOGGED IN\nsdkObject: "+a.g+"\nuserID: "+q.myUID+"\nprovider: "+q.providerID+
"\nemail: "+q.myEmail+"\nisEmailVerified: "+q.isEmailVerified+"\nusername: "+q.username+"\nphone: "+q.phoneNo+"\nphotoURL: "+q.photoURL+"\n "):a.debug&&console.log("LOGGED OUT\nsdkObject: "+a.g+"\n ");e.status="success";e.ka=q;e.la=r;c();r.gd=0;f.Ab[a.g]=1})}function ja(q){f.L[a.g]=a.g===f.ab?f.Bb.Gc(q):f.Bb.Gc(q,a.g);"undefined"===typeof f.K[a.g]&&(f.K[a.g]={});a.wc&&(f.Gd[a.g]=f.tc.wd(f.L[a.g]),f.kd&&f.tc.sd(!0));a.xc&&(f.Hd[a.g]=f.td.xd(f.L[a.g]));a.Ac&&(f.Jd[a.g]=f.storage.Ad(f.L[a.g]));a.Cb&&
(f.Fd[a.g]=f.ld.ud(f.L[a.g]));a.zc&&(f.Kc[a.g]=f.Sd.zd(f.L[a.g]),q=f.Kc[a.g],q.ae.Ed=1E3*a.Rd,q.pd=a.Qd);a.yc&&(f.Id[a.g]=f.performance.yd(f.L[a.g]));a.uc&&f.qc.Cd(f.L[a.g],{Od:new f.qc.dd(a.Pd),Dd:!0});a.vc?(f.bb[a.g]=f.h.vd(f.L[a.g]),fb()):(f.Ab[a.g]=1,e.status="success",c())}if("init"===a.action)if("undefined"===typeof f.ab&&(f.ab=a.g),a.g===f.ab){var h=["initializeAppCheck","ReCaptchaV3Provider"],k="createUserWithEmailAndPassword deleteUser getAdditionalUserInfo getAuth linkWithCredential linkWithPhoneNumber linkWithPopup linkWithRedirect onAuthStateChanged sendEmailVerification sendPasswordResetEmail setPersistence signInAnonymously signInWithCredential signInWithEmailAndPassword signInWithPhoneNumber signInWithPopup signInWithRedirect signInWithCustomToken signOut unlink updateEmail updatePassword updatePhoneNumber updateProfile useDeviceLanguage AuthCredential EmailAuthCredential EmailAuthProvider FacebookAuthProvider GithubAuthProvider GoogleAuthProvider OAuthProvider OAuthCredential PhoneAuthCredential PhoneAuthProvider RecaptchaVerifier TwitterAuthProvider".split(" "),
l="enableLogging endAt endBefore equalTo get getDatabase goOffline goOnline increment limitToFirst limitToLast off onChildAdded onChildChanged onChildMoved onChildRemoved onDisconnect onValue orderByChild orderByKey orderByValue push query ref set remove runTransaction serverTimestamp startAfter startAt update".split(" "),m="addDoc arrayRemove arrayUnion clearIndexedDbPersistence collection collectionGroup deleteDoc deleteField disableNetwork doc documentId enableIndexedDbPersistence enableMultiTabIndexedDbPersistence enableNetwork endAt endBefore getDoc getDocFromCache getDocFromServer getDocs getFirestore increment initializeFirestore limit limitToLast loadBundle namedQuery onSnapshot onSnapshotsInSync orderBy query refEqual runTransaction serverTimestamp setDoc setLogLevel snapshotEqual startAfter startAt terminate updateDoc waitForPendingWrites where writeBatch".split(" "),
g="deleteObject getDownloadURL getMetadata getStorage list listAll ref updateMetadata uploadBytes uploadBytesResumable uploadString".split(" "),t="getAnalytics initializeAnalytics logEvent setAnalyticsCollectionEnabled setUserId setUserProperties".split(" "),E=["fetchAndActivate","getAll","getRemoteConfig"],Y=["getPerformance","trace"];a.Qc="";a.Oc="";a.Pc="";const q="https://www.gstatic.com/firebasejs/"+a.version+"/firebase-";var v="",K="";function r(u,G,z){v+="import {";K+="globalThis.sparshaFirebase."+
z+"={";G=JSON.parse('["'+G.replaceAll("\n",'","')+'"]');G.forEach(function(n){n=u.indexOf(n);-1<n&&u.splice(n,1)});u.forEach(function(n){if("database"!==z||"ref"!==n&&"endAt"!==n&&"endBefore"!==n&&"increment"!==n&&"limitToLast"!==n&&"query"!==n&&"runTransaction"!==n&&"serverTimestamp"!==n&&"startAfter"!==n&&"startAt"!==n)v+=n+", ",K+=n+":"+n+",";else{var Ea=n+z;v+=n+" as "+Ea+", ";K+=n+":"+Ea+","}});"appcheck"===z&&(z="app-check");"remoteconfig"===z&&(z="remote-config");v+='  } from "'+q+z+'.js";';
K+="};"}"undefined"!==typeof window.cordova&&(a.Cb=!1);r(["deleteApp","getApp","initializeApp"],a.Td,"app");a.uc&&r(h,"","appcheck");a.vc&&r(k,a.Ud,"auth");a.wc&&r(l,a.Vd,"database");a.xc&&r(m,a.Wd,"firestore");a.Ac&&r(g,a.Xd,"storage");a.Cb&&r(t,a.Oc,"analytics");a.zc&&r(E,a.Qc,"remoteconfig");a.yc&&r(Y,a.Pc,"performance");f.jd=function(){ja(a.Eb)};f.kc=0;function Q(){var u=document.createElement("script");u.type="module";u.innerHTML=v+K+"globalThis.sparshaFirebase._isLoaded=1;globalThis.sparshaFirebase._callInitApp();";
document.getElementsByTagName("head")[0].appendChild(u)}Q();var gb=setTimeout(function(){0===f.kc?(a.debug&&console.error("TIMEOUT\nsdkObject: "+a.g),a.md&&Q(),e.status="timeout",c()):clearTimeout(gb)},1E3*a.de)}else ja(a.Eb);else ja(a.Eb)}else"disconnect"===a.action&&f.Bb.qd(f.L[a.g])})}});"use strict";
self.O.W(class extends self.ma{constructor(d){super(d,"sparsha_firebase_auth");var b=this;x(this,"domSync_sparsha_fAuth",function(a){if("RemoveRecaptcha"===a.action){var c=document.createElement("style");c.innerHTML=".grecaptcha-badge{visibility: hidden;}";document.head.appendChild(c)}else if("PopupOauthSafe"===a.action){a.i=0;var e=globalThis.Gb,f=e.bb[a.g];window.document.getElementById(a.nd).onclick=function(){h()};function h(){if(0===a.o){var k=new e.h.Ea;a.Ec&&k.setCustomParameters({prompt:"select_account"})}else 1===
a.o?k=new e.h.Ca:2===a.o?k=new e.h.H("apple.com"):3===a.o?k=new e.h.Ha:4===a.o?k=new e.h.Da:5===a.o?k=new e.h.H("microsoft.com"):6===a.o&&(k=new e.h.H("yahoo.com"));var l;e.h.Tc(f,k).then(m=>{a.ja=e.h.Fb(m).ja;l=m;var g=e.na(m.v,a.g);a.ka=g.ua;a.la=g.va;a.i=1;if(0===a.o)a.m=e.h.Ea.F(m);else if(1===a.o){a.m=e.h.Ca.F(l);var t=l.v.cb.split("?")[0]+"?access_token="+a.m.pc;a.m=JSON.stringify(a.m);e.h.fb(e.K[a.g].v,{cb:t}).then(()=>{a.eb=1;a.Mc=t;p(b,"run_sparsha_fAuthBasic"+a.wa,a)}).catch(E=>{a.eb=0;
a.errorCode=E.code;a.errorMessage=E.message;p(b,"run_sparsha_fAuthBasic"+a.wa,a)})}else 2===a.o?a.m=e.h.H.F(m):3===a.o?a.m=e.h.Ha.F(m):4===a.o?a.m=e.h.Da.F(m):5<=a.o&&(a.m=e.h.H.F(m));a.m=JSON.stringify(a.m);p(b,"run_sparsha_fAuthBasic"+a.wa,a)}).catch(m=>{a.i=0;a.errorCode=m.code;a.errorMessage=m.message;p(b,"run_sparsha_fAuthBasic"+a.wa,a)})}}});x(this,"domAsync_sparsha_fAuth",async function(a){var c={i:0},e=globalThis.Gb,f=e.bb[a.g];if("Signupemail"===a.action||"Signinemail"===a.action||"Signupname"===
a.action||"Signinname"===a.action){var h="",k="";h="Signupemail"===a.action||"Signupname"===a.action?"createUserWithEmailAndPassword":"signInWithEmailAndPassword";k="Signupname"===a.action||"Signinname"===a.action?a.username.replace(/ /g,"")+"@"+a.domain:a.email;e.Z[a.g]=1;await e.h[h](f,k,a.password).then(g=>{var t=new e.h.ad(k,a.password,"password");g=e.na(g.v,a.g);c.ka=g.ua;c.la=g.va;c.m=JSON.stringify(t);c.i=1}).catch(g=>{e.Z[a.g]=0;c.i=0;c.errorCode=g.code;c.errorMessage=g.message});"Signupname"===
a.action&&c.i&&await e.h.fb(e.K[a.g].v,{displayName:a.username}).then(()=>{c.Lc=1}).catch(g=>{c.Lc=0;c.errorCode=g.code;c.errorMessage=g.message})}else if("VerifyEmail"===a.action)await e.h.Zd(e.K[a.g].v).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("UpdateEmail"===a.action)await e.h.ee(e.K[a.g].v,a.Kd).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("ResetPassword"===a.action)await e.h.$d(f,a.email).then(()=>{c.i=
1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("UpdatePassword"===a.action)await e.h.fe(e.K[a.g].v,a.password).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("RenderRecaptcha"===a.action)h=document.getElementById("SparshaFirebaseCaptcha"),null===h&&(h=document.createElement("BUTTON"),h.display="none",h.id="SparshaFirebaseCaptcha",document.body.appendChild(h)),e.kb=new e.h.ed("SparshaFirebaseCaptcha",{size:"invisible",theme:a.ce},
f),await e.kb.Yd().then(g=>{e.hd=g;c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("SendPhoneNumber"===a.action)await e.h.be(f,a.Md,e.kb).then(g=>{e.lb=g;c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("SubmitOtp"===a.action)e.Z[a.g]=1,await e.lb.confirm(a.Nc).then(g=>{c.ja=e.h.Fb(g).ja;c.m=e.h.bd.credential(e.lb.he,a.Nc);g=e.na(g.v,a.g);c.ka=g.ua;c.la=g.va;c.m=JSON.stringify(c.m);c.i=1}).catch(g=>{e.Z[a.g]=0;c.i=0;c.errorCode=g.code;c.errorMessage=
g.message});else if("SignOut"===a.action)await e.h.Uc(f).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message}),"undefined"!==typeof window.cordova&&"undefined"!==typeof window.cordova.plugins&&"undefined"!==typeof window.cordova.plugins.Dc&&await window.cordova.plugins.Dc.h.Uc(),"undefined"!==typeof window.plugins&&"undefined"!==typeof window.plugins.Fc&&await window.plugins.Fc.logout(),"undefined"!==typeof window.Cc&&await window.Cc.logout();else if("UpdateUsername"===a.action)await e.h.fb(e.K[a.g].v,
a.ge).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("DeleteUser"===a.action)await e.h.rd(e.K[a.g].v).then(()=>{c.i=1}).catch(g=>{c.i=0;c.errorCode=g.code;c.errorMessage=g.message});else if("PopupOauth"===a.action){e.Z[a.g]=1;0===a.o?(h=new e.h.Ea,a.Ec&&h.setCustomParameters({prompt:"select_account"})):1===a.o?h=new e.h.Ca:2===a.o?h=new e.h.H("apple.com"):3===a.o?h=new e.h.Ha:4===a.o?h=new e.h.Da:5===a.o?h=new e.h.H("microsoft.com"):6===a.o&&(h=new e.h.H("yahoo.com"));
var l;await e.h.Tc(f,h).then(g=>{c.ja=e.h.Fb(g).ja;l=g;var t=e.na(g.v,a.g);c.ka=t.ua;c.la=t.va;0===a.o?c.m=e.h.Ea.F(g):2===a.o?c.m=e.h.H.F(g):3===a.o?c.m=e.h.Ha.F(g):4===a.o?c.m=e.h.Da.F(g):5<=a.o&&(c.m=e.h.H.F(g));c.m=JSON.stringify(c.m);c.i=1}).catch(g=>{e.Z[a.g]=0;c.i=0;c.errorCode=g.code;c.errorMessage=g.message});if(1===a.o&&1===c.i){c.m=e.h.Ca.F(l);var m=l.v.cb.split("?")[0]+"?access_token="+c.m.pc;c.m=JSON.stringify(c.m);await e.h.fb(e.K[a.g].v,{cb:m}).then(()=>{c.eb=1;c.Mc=m}).catch(g=>{c.eb=
0;c.errorCode=g.code;c.errorMessage=g.message})}}return c})}});
